services:
  traefik:
    image: docker.io/traefik:v3.6.7
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./backend/docker/local/traefik/traefik.yml:/etc/traefik/traefik.yml:rw
      - ./backend/docker/local/traefik/logs:/var/log/traefik
    networks:
      - nextgen_local_nw
    labels:
      - "traefik.enable=true"

      # ✅ Retry middleware (dynamic via docker provider)
      - "traefik.http.middlewares.retry-mw.retry.attempts=3"
      - "traefik.http.middlewares.retry-mw.retry.initialinterval=500ms"

  api: &api
    build:
      context: .
      dockerfile: ./backend/docker/local/fastapi/Dockerfile
    volumes:
      - .:/nextgen-bank-fastapi
      - ./backend/app/logs:/nextgen-bank-fastapi/backend/app/logs
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.env.local
    depends_on:
      - postgres
      - mailpit
      - redis
      - rabbitmq
    command: /start.sh
    networks:
      - nextgen_local_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.middlewares=retry-mw@docker"
      - "traefik.http.routers.api.service=api-service"
      - "traefik.http.services.api-service.loadbalancer.server.port=8000"

  mailpit:
    image: docker.io/axllent/mailpit:v1.20.3
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - nextgen_mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - nextgen_local_nw

  postgres:
    build:
      context: .
      dockerfile: ./backend/docker/local/postgres/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - nextgen_local_db:/var/lib/postgresql/data
    env_file:
      - ./.envs/.env.local
    networks:
      - nextgen_local_nw

  prometheus:
    image: prom/prometheus:v2.55.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./backend/docker/local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - nextgen_local_nw

  grafana:
    image: grafana/grafana:11.2.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - nextgen_local_nw

  redis:
    image: docker.io/redis:7.0-alpine
    command: redis-server --appendonly yes
    networks:
      - nextgen_local_nw
  rabbitmq:
    image: docker.io/rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - nextgen_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - nextgen_local_nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.routers.rabbitmq.rule=Host(`rabbitmq.localhost`)"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      
  celeryworker:
    <<: *api
    ports: []
    command: /start-celeryworker.sh
  flower:
    <<: *api
    ports:
      - "5555:5555"
    volumes:
      - nextgen_flower_data:/flower
    command: /start-celeryflower.sh
    depends_on:
      - redis
      - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.entrypoints=web"
      - "traefik.http.routers.flower.rule=Host(`flower.localhost`)"
      - "traefik.http.routers.flower.service=flower-service"
      - "traefik.http.services.flower-service.loadbalancer.server.port=5555"
  celerybeat:
    <<: *api
    ports: []
    command: /start-celerybeat.sh
    

networks:
  nextgen_local_nw:
    external: true

volumes:
  nextgen_local_db:
  nextgen_mailpit_data:
  grafana_data:
  nextgen_flower_data:
  nextgen_rabbitmq_data:
